In [1]:
import final
import numpy as np

In [2]:
final.read_temperature("/workspaces/CP1-24-final/OA002_sinewalktrial.md")

'33'

In [3]:
final.filename_lister('/workspaces/CP1-24-final', 'sinewalktrial', '.md')

['OA001_sinewalktrial.md', 'OA002_sinewalktrial.md']

In [4]:
final.get_coordinates('/workspaces/CP1-24-final/OA001_sinewalktrial.csv')

(array([-8761185.94823218, -8761169.18003461, -8761169.18003461,
        -8761168.43836433, -8761168.62405989]),
 array([5306383.6854801 , 5306371.29832689, 5306371.29832689,
        5306370.79201546, 5306370.79201546]))

In [8]:
final.numpy_wrapper_fft(np.array([-8761185.94823218, -8761169.18003461, -8761169.18003461,
        -8761168.43836433, -8761168.62405989]), np.array([5306383.6854801 , 5306371.29832689, 5306371.29832689,
        5306370.79201546, 5306370.79201546]), 3)

(array([4.24510183e+07 +0.j        , 7.33510844e+00-17.63326524j,
        7.31306734e+00 -7.28189651j, 7.29102623e+00 -3.00713057j,
        7.28189651e+00 +0.j        , 7.29102623e+00 +3.00713057j,
        7.31306734e+00 +7.28189651j, 7.33510844e+00+17.63326524j]),
 [np.float64(0.0),
  np.float64(5.050746353354533),
  np.float64(10.101492706709067),
  np.float64(15.152239060063598),
  np.float64(20.202985413418133),
  np.float64(25.253731766772663),
  np.float64(30.304478120127197),
  np.float64(35.355224473481734)])

In [5]:
final.shift_coordinates(np.array([-8761185.94823218, -8761169.18003461, -8761169.18003461,
        -8761168.43836433, -8761168.62405989]),
 np.array([5306383.6854801 , 5306371.29832689, 5306371.29832689,
        5306370.79201546, 5306370.79201546]))

(array([ 0.        , 16.76819757, 16.76819757, 17.50986785, 17.32417229]),
 array([  0.        , -12.38715321, -12.38715321, -12.89346464,
        -12.89346464]))

In [6]:
final.resample_data(np.array([ 0.        , 16.76819757, 16.76819757, 17.50986785, 17.32417229]), np.array([  0.        , -12.38715321, -12.38715321, -12.89346464,
        -12.89346464]), 3)

(array([ 0.        ,  2.47488176,  4.94976351,  7.42464527,  9.89952702,
        12.37440878, 14.84929053, 17.32417229]),
 array([  0.        ,  -1.82826683,  -3.65653367,  -5.4848005 ,
         -7.31306734,  -9.14133417, -10.969601  , -12.76669701]))

In [7]:
final.get_frequency_axis([ 0.        ,  2.47488176,  4.94976351,  7.42464527,  9.89952702,
        12.37440878, 14.84929053, 17.32417229], 1/100)

[0.0,
 5.050746343534408,
 10.101492687068816,
 15.152239030603223,
 20.202985374137633,
 25.25373171767204,
 30.304478061206446,
 35.35522440474085]

In [11]:
final.numpy_wrapper_ifft([4.24510183e+07 +0.j        , 7.33510844e+00-17.63326524j,
        7.31306734e+00 -7.28189651j, 7.29102623e+00 -3.00713057j,
        7.28189651e+00 +0.j        , 7.29102623e+00 +3.00713057j,
        7.31306734e+00 +7.28189651j, 7.33510844e+00+17.63326524j])

array([5306383.68253757+0.j, 5306381.85427073+0.j, 5306380.0260039 +0.j,
       5306378.19773706+0.j, 5306376.36947023+0.j, 5306374.54120339+0.j,
       5306372.71293656+0.j, 5306370.91584055+0.j])